### ISSUE TITLE
Rendering Issues (Text Placeholder)

### ISSUE THREAD

**Issue by jamiemcg** [openannotation/annotator#550]
Is there any known reason for the errors shown in the screenshot?
- The input text placeholders end in: "**â€¦**"
- The gradient seems to be going in the wrong direction for some elements (see cancel and save buttons)

How would I fix this?

![image](https://cloud.githubusercontent.com/assets/6209007/8910080/b700033a-347c-11e5-8a34-87834cc47ca4.png)

**Comment by nickstenning** [comment]
What version of Annotator are you using? This looks like a bug that was fixed quite some time ago.

**Comment by jamiemcg** [comment]
Annotator v1.2.10 with jQuery v2.1.4.
Downloaded it again and it fixed the gradient error but there is still an error with placeholders:

![image](https://cloud.githubusercontent.com/assets/6209007/8927620/98488b8a-3510-11e5-8f4b-73382fea9686.png)

**Comment by tilgovi** [comment]
I cannot reproduce this. Do you have an uncommon charset meta tag on this page?

**Comment by tilgovi** [comment]
Bump.

**Comment by cwbuecheler** [comment]
I'm getting this issue, too, while working on a local file, using v2.0.0-alpha3, grabbed from this page: https://github.com/openannotation/annotator/releases. I don't think there's anything particularly odd about my charset. Here's the code in its entirety:

``` html
<!DOCTYPE html>
<html charset="UTF-8">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Annotator Test</title>
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="annotator.min.js"></script>
    <script>
      $(document).ready(function() {
        var textDiv = document.getElementsByClassName('content')
        var app = new annotator.App();
        app.include(annotator.ui.main, {element: textDiv[0]});
        app.start();
      });
    </script>
  </head>
  <body>
    <div class="content">
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget velit sem. Nullam id nisl dapibus diam semper placerat sed in elit. Nam lacinia erat et rhoncus euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam vel consequat lorem. Curabitur magna nisi, egestas sit amet mauris sed, hendrerit scelerisque felis. Suspendisse at euismod purus.
      </p>
    </div>
  </body>
</html>
```

Screenshot of the issue: 
<img width="839" alt="annotator" src="https://cloud.githubusercontent.com/assets/1482810/17143149/716580de-5320-11e6-88d7-6d296913b4af.png">

I checked the code itself and it's grabbing the placeholder from the textarea's label, and the label is clearly set to just "Comments" so I'm unsure where the additional characters are coming from ... do you think it could be the page's dependency on a very old version of jQuery?

Edited to add: browser is Chrome Version 51.0.2704.106 (64-bit) on OSX El Capitan.

**Comment by jamiemcg** [comment]
If I recall correctly, this error only existed when tested locally. It seemed to disappear when it was deployed.

**Comment by cwbuecheler** [comment]
OK, thanks. I'll see how it looks on a productions server before worrying about it.

**Comment by tilgovi** [comment]
@cwbuecheler please let us know what you find.

**Comment by cwbuecheler** [comment]
Running annotator.js on a local server (either Apache, Nginx, or Express), instead of directly browsing to an html file on my drive, seems to fix the issue, so while I don't really know what the problem is/was ... it's not a problem for me anymore. :)

**Comment by tilgovi** [comment]
That's a known limitation in certain browsers. Not all browsers will do XHR
on file: URLs.

**Comment by tilgovi** [comment]
I don't know why the character display issue, maybe to do with loading remote fonts??? But you'll have other problems on file: URLs.

I'm going to close this. Please notify and we can reopen if anyone experiences this issue when serving over HTTP.
