### ISSUE TITLE
Is http://www.annotatorjs.org/ still working?

### ISSUE THREAD

**Issue by peterldowns** [openannotation/annotator#688]
Seems like the site is down for me, and with it, all of the docs...

**Comment by radekwroblewski** [comment]
Same issue here.
Fortunatelly I've managed to build the offline docs from the release source files, allthough the online showcase would really come in handy.

**Comment by tilgovi** [comment]
@AndrewMagliozzi can you help us out here? I'm happy to maintain this, but you're the registrant, right?

**Comment by AndrewMagliozzi** [comment]
> Hey Randall,

I sure am. What do you need?

Feel free to email me andrew@finalsclub.org

I tried to ping you and nick but both emails bounced.

**Comment by tilgovi** [comment]
Should be fixed.

**Comment by radekwroblewski** [comment]
Not quite:
* http://docs.annotatorjs.org/ still doesn't work
* annotator is not initialized on the main page (following stacktrace is thrown on browser console):
assets.annotateit.org/annotator/v1.2.10/annotator.min.css:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
annotator-full.min.js:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
glyph-logo.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
(index):286 Uncaught TypeError: $(...).annotator is not a function
    at initAnnotator ((index):286)
    at initAnnotator:1

**Comment by nickstenning** [comment]
1. The CNAME for `docs.annotatorjs.org` is fixed. Looks like the RTD project needs a build, though, as the asset links there point to an old RTD CDN domain that doesn't work any more.

2. Unfortunately I have no control over `annotateit.org`. That domain is still in the control of Open Knowledge, and they've apparently dropped the DNS zone (as they did with `annotatorjs.org`).

**Comment by AndrewMagliozzi** [comment]
> Instead of annotateit I can set up a sub domain of AnnotatorJS perhaps demo.annotatorjs.org?

If you want me to do that just shoot me an email saying where to point the cname.

**Comment by kyle-wendling** [comment]
Checking out annotator, site homepage still seems broken, so there's no working demo, 
I think the primary issue is the .js files are not resolving, javascript console for the index page shows errors:
GET http://assets.annotateit.org/annotator/v1.2.10/annotator.min.css 0 ()
(index):242 GET **http://assets.annotateit.org/annotator/v1.2.10/annotator-full.min.js** 0 ()
(index):296 GET http://annotatorjs.org/css/images/glyph-logo.png 404 (Not Found)
(index):286 Uncaught TypeError: $(...).annotator is not a function
    at initAnnotator ((index):286)
    at initAnnotator:1

http://assets.annotateit.org/annotator/v1.2.10/annotator-full.min.js <- does not resolve

**Comment by jblotus** [comment]
+1 was trying to show this to product manager as a possible solution for annotations and ran into this.
